#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout (binding = 0, rgba8) uniform image2D RWImage;

void main()
{
	float X = float(gl_GlobalInvocationID.x) / float(gl_WorkGroupSize.x);
	float Y = float(gl_GlobalInvocationID.y) / float(gl_WorkGroupSize.y);

	vec4 Color = vec4(X, Y, X, 1.0);
	imageStore(RWImage, ivec2(gl_GlobalInvocationID.xy), Color);
}
